version: '3.8'
services:
    api:
        container_name: api
        build:
            context: ./docker/nodejs
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - mysql
        networks:
            - backend
        ports:
            - 3030:3030
        volumes:
            - ./api:/www
        command: npm start
    mysql:
        container_name: mysql
        image: mysql:latest
        restart: always
        networks:
            - backend
        ports:
            - 3306:3306
networks:
    backend:
