version: "3.8"
services:
    api:
        container_name: api
        build:
            context: ./docker/nodejs
            dockerfile: Dockerfile
            volumes:
            networks:
                - backend
            ports:
            depends_on:
              command:
    mysql:
        container_name: mysql
        image: mysql
        networks:
                - backend
        ports:
        environment:
networks:
    backend:
