version: '3.8'

services:
    api:
        container_name: api
        build:
            context: ./docker/nodejs
            dockerfile: Dockerfile
        depends_on:
            - mysql
        restart: always
        ports:
            - 3030:3030
        volumes:
            - ./api:/www
        networks:
            - backend-network
        command: npm install
        command: npm start
    mysql:
        container_name: db
        image: mysql:latest
        ports:
            - 3306:3306
        networks:
            - backend-network
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_DATABASE: db1
            MYSQL_USER: user1
            MYSQL_PASSWORD: 1234

networks:
    backend-network:
