version: '3.8'

services:
    api:
        container_name: demo-app-container:api
        build:
            context: ./docker/nodejs
            dockerfile: Dockerfile
        depends_on:
            - mysql
        restart: always
        ports:
            - 3030:3030
        volumes:
            - ./api:/www
        networks:
            - backend-network
        command: npm start
    mysql:
        image: mysql:latest
        ports:
            - 3306:3306
        networks:
            - backend-network
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_DATABASE: test
            MYSQL_USER: root
            MYSQL_PASSWORD: mysql

networks:
    backend-network:
