version: "3.8"
services:
    api:
      container_name: api
      build:
        context: ./docker/nodejs
        dockerfile: Dockerfile
        volumes:
            - ./api: /www
        networks:
            - backend
        ports:
            - 3030:3030
        depends_on:
            - mysql
        command: npm start
    mysql:
        container_name: sql
        image: mysql
        networks:
            - backend
        ports:
            - 3306:3306
        environment:
networks:
    backend:
