version: "3.8"
services:
    api:
      container_name: api
      volumes:
        - ./api: /www
      network:
        - backend
    sql:
      container_name: sql
      network:
        - backend
networks:
    backend:
